name: Working with Environments

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    - name: Run job
      run: az ml job create --stream --file src/job-dev.yml --workspace-name MLOpsLab --resource-group MLOpsLab
  train-prod:
    runs-on: ubuntu-latest
    environment: Production
    needs: train-dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    - name: Run job
      run: az ml job create --stream --file src/job-prod.yml --workspace-name MLOpsLab --resource-group MLOpsLab
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    needs: train-prod
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      - name: Create endpoint
        run: az ml online-endpoint create --name lcf-diabetes-endpoint -f src/create-endpoint.yml --workspace-name MLOpsLab --resource-group MLOpsLab
      - name: Deploy
        run: az ml online-deployment create --name mlflow-deployment --endpoint lcf-diabetes-endpoint -f src/mlflow-deployment.yml --all-traffic --workspace-name MLOpsLab --resource-group MLOpsLab     
